version: '3.6'
services:

  jenkins:
    image: jenkins.nginx.docker:lts
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins-${AERPAW_UUID:-deadbeef-dead-beef-dead-beefdeadbeef}
    ports:
      - '2022:22'
      - '50000:50000'
      - '50022:50022'
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=default123!
      - UID_JENKINS=${UID_JENKINS:-1000}
      - GID_JENKINS=${GID_JENKINS:-1000}
      - JENKINS_OPTS=${JENKINS_OPTS:-"--prefix=/jenkins"}
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-${AERPAW_UUID:-deadbeef-dead-beef-dead-beefdeadbeef}
    ports:
      - ${NGINX_HTTP_PORT:-8080}:80
      - ${NGINX_HTTPS_PORT:-8443}:443
    volumes:
      - ${NGINX_INDEX:-./nginx/index.html}:/usr/share/nginx/html/index.html
      - ${NGINX_CONF:-./nginx/default.conf}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_DIR:-./ssl}:/etc/ssl
      - ${NGINX_LOG_DIR:-./logs/nginx}:/var/log/nginx
    restart: always